export default {
  GET_PAGING: "AboutManager/get-paging",
  GET_PAGING_CUSTOMER_CARE: "AboutManager/get-paging-customer-care",
  GET_PAGING_ABOUT: "AboutManager/get-paging-about",
  GET_PAGING_ATTACK: "AboutManager/get-paging-attack",
  COMBOBOX: "AboutManager/get-combobox",
  COMBOBOX_ABOUT_MANAGER: "AboutManager/get-combobox-about-manager",
  COMBOBOX_LIST_ABOUT_MANAGER: "AboutManager/combobox-list-about-manager",
  CREATE: "AboutManager/create",
  CREATE_ATTACK: "AboutManager/create-attack",
  UPDATE: "AboutManager/update",
  UPDATE_ATTACK: "AboutManager/update-attack",
  UPDATE_DETAIL: "AboutManager/update-detail",
  DELETE: "AboutManager/delete",
  DELETE_ATTACK: "AboutManager/delete-attack",
  GET_BY_ID: "AboutManager/get-by-id",
  GET_DETAIL: "AboutManager/get-detail",
};
