export default {
  NEWS_CONTENT_TREE_VIEW: 'newsContent/get-treeview',
  NEWS_CONTENT_TREE_VIEW_MODAL: 'newsContent/get-treeview-modal-content',
  NEWS_CONTENT_CREATE: "newsContent/create",
  NEWS_CONTENT_UPDATE: "newsContent/update",
  NEWS_CONTENT_DELETE: "newsContent/delete",
  NEWS_CONTENT_GET_BY_ID: "newsContent/get-by-id",
  NEWS_CONTENT_GET_COMBOBOX_NEWS_CONTENT_TYPE: "newsContent/get-combobox-news-content-type",
  COMBOBOX_NEWS_CONTENT: "newsContent/get-combobox-news-content",
  NEWS_CONTENT_GET_PAGING: "newsContent/get-paging",
  NEWS_CONTENT_GET_PAGING_AUTO_POST: "newsContent/get-paging-auto",
  NEWS_CONTENT_NEWS_AUTHOR: "newsContent/news-author",
  COPY_LINK: "newsContent/copy-link",
  READ_LINK: "newsContent/read-link",
  POST_NEW: "newsContent/post-news",
  AUTO_TIME: "newsContent/update-time",
  SCHEDULER: "newsContent/schedule-save",
  SCHEDULE_CONFIG: "newsContent/schedule-config",
};
